version: '3.4'
networks:
  grupo8:
# volumes:
#   grupo8-keycloak-data:
#     external: true
services:
  # Keycloak
  keycloak:
    container_name: keycloak
    image: jboss/keycloak:latest
    ports:
      - 8090:8080
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=a12345678
      - KEYCLOAK_FRONTEND_URL=http://localhost:8090/auth
    volumes:
      - ./data:/opt/jboss/keycloak/standalone/data
    networks:
      - grupo8
  auth-backend:
    container_name: auth-backend
    build:
      context: docker-auth-backend
      dockerfile: Dockerfile
    image: auth-backend:latest
    ports:
      - 8080:8080
    networks:
      - grupo8

